version: '3.8'

services:
  ragmcp:
    build:
      context: ./ragMCP
      dockerfile: Dockerfile
    container_name: ragmcp_server
    networks:
      - app-network
    ports:
      - "8080:8080"
    volumes:
      - ./ragMCP:/app
    stdin_open: true
    tty: true
    # Auto-start MCP server so agents can connect to it
    command: ["python", "main.py"]

    secrets:
      - source: app_ini
        target: secrets.ini                 # will appear at /run/secrets/secrets.ini
    environment:
      SECRETS_INI_FILE: /run/secrets/secrets.ini
    
  agentserver:
    build:
      context: ./agentServer
      dockerfile: Dockerfile
    container_name: agent_server
    depends_on:
      - ragmcp
    networks:
      - app-network
    ports:
      - "8766:8766"
    secrets:
      - source: app_ini
        target: secrets.ini
    environment:
      - RAGMCP_URL=http://ragmcp:8080
      - SECRETS_INI_FILE=/run/secrets/secrets.ini
    volumes:
      - ./agentServer:/app
    stdin_open: true
    tty: true
    # Keep container running without auto-starting for debugging
    command: ["tail", "-f", "/dev/null"]

networks:
  app-network:
    driver: bridge

secrets:
  app_ini:
    file: ./secrets.ini 