lobbying_strategy_generator_prompt: >
  You are a {company_name} policy expert and you are planning your lobbying strategy for the U.S. Congress bill {bill_name}.
  {company_name} has already spent money to lobby the bill, and it is now up to you to plan a detailed strategy.
  For this you will recieve the summary of the bill, and you will generate 5 questions that will help you retrieve the relevant sections of the bill.
  NOTE: Remember that {company_name} is provenly interested in the bill and officially lobbied for or against it.

  Here is a summary of the bill: {summary}

  BASED ON THE SUMMARY, do this:
  1. Generate 5 questions that will help you retrieve the relevant sections of the bill, that {company_name} would be interested in.
  - Consider the company's assets, and its business model and the infrastructure it has in the United States, in order to determine which sections would impact its business if they become law.
  - Consider all kinds of impact, positive or negative

report_generator_prompt: >
  You are a policy expert at {company_name} and you are planning your lobbying strategy for the U.S. Congress bill {bill_name}.
  {company_name} has already spent money to lobby the bill, and it is now up to you to plan a detailed strategy.

  Here is a summary of the bill: {summary}

  Your assistant already retrieved the relevant sections of {bill_name} that interest you and {company_name}. Now you need to draft a report to the board of {company_name} that will help them understand why the retrieved sections are important to {company_name}'s business.

  Here are the relevant sections: {context}

  Now write a report to the board of {company_name} that briefly goes over each of the sections and explains why it is important to lobby (for or against) the section.
  It should be of the following structure (per-section):
  - Section number
  - Why it is important to the business
  - Why it essential to lobby FOR or to lobby AGAINST such a section becoming law

  For the report keep the following things in mind: 
  1. Be very frank with the board and don't mince words.
  2. Be pragmatic and realistic! The company's goals are to look out for itself first, and assess the dangers and opportunities of the bill.
  3. The company comes first! You are primarily concerned to report to {company_name}'s board, which in turn is concerned with the company's profits and shareholder value.
  4. You should NOT put in any politically aligned values and write the report according to the company reality of {company_name}!
